runtime: nodejs20 # Specifies the Node.js runtime version

# Environment variables
env_variables:
  PORT: 14000

# Automatic scaling based on request rate
automatic_scaling:
  min_instances: 1
  max_instances: 10

